"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Table, TableHeader, TableBody, TableRow, TableCell, TableHead } from "@/components/ui/table";
import { formatRelativeTime } from "@/lib/utils";
import { reportsApi } from "@/lib/api";
import { FileText, Search, Download, AlertTriangle, RefreshCw } from "lucide-react";

const formatLabels: Record<string, string> = {
  pdf: "PDF",
  html: "HTML",
  json: "JSON",
};

export default function ReportsPage() {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [pageSize] = useState(20);

  const { data, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: ["reports", { page, pageSize }],
    queryFn: () => reportsApi.list({ page, page_size: pageSize }),
  });

  const reports = data?.items || [];
  const totalReports = data?.total || 0;

  const filteredReports = search
    ? reports.filter(
        (r) =>
          r.title.toLowerCase().includes(search.toLowerCase()) ||
          r.case_id.toLowerCase().includes(search.toLowerCase())
      )
    : reports;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
          <p className="text-muted-foreground">Generated investigation reports</p>
        </div>
        <Button variant="outline" onClick={() => refetch()} disabled={isFetching}>
          <RefreshCw className={`w-4 h-4 mr-2 ${isFetching ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-lg">All Reports ({totalReports})</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="relative max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search by title or case ID..."
              className="pl-9"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          {error && (
            <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-sm flex items-center gap-2">
              <AlertTriangle className="w-4 h-4" />
              Failed to load reports: {error instanceof Error ? error.message : "Unknown error"}
            </div>
          )}

          {isLoading ? (
            <div className="py-12 text-center text-muted-foreground">Loading reports...</div>
          ) : filteredReports.length === 0 ? (
            <div className="py-12 flex flex-col items-center justify-center text-muted-foreground">
              <FileText className="w-12 h-12 mb-4 opacity-30" />
              <p className="text-lg font-medium">No Reports Found</p>
              <p className="text-sm mt-1">Generate a report from a case to see it listed here</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Title</TableHead>
                    <TableHead>Case</TableHead>
                    <TableHead>Format</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Created</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredReports.map((r) => (
                    <TableRow key={r.id}>
                      <TableCell className="font-medium">{r.title}</TableCell>
                      <TableCell className="font-mono text-xs text-muted-foreground">{r.case_id}</TableCell>
                      <TableCell>
                        <Badge variant="outline">{formatLabels[r.format] || r.format}</Badge>
                      </TableCell>
                      <TableCell className="text-muted-foreground">{r.generated_by}</TableCell>
                      <TableCell className="text-muted-foreground">{formatRelativeTime(r.created_at)}</TableCell>
                      <TableCell className="text-right">
                        {r.file_path ? (
                          <a
                            href={r.file_path}
                            target="_blank"
                            rel="noopener noreferrer"
                            title="Download report"
                            className="inline-flex items-center justify-center h-10 w-10 rounded-md hover:bg-accent hover:text-accent-foreground transition-colors"
                          >
                            <Download className="w-4 h-4" />
                          </a>
                        ) : (
                          <Button variant="ghost" size="icon" disabled title="No file available">
                            <Download className="w-4 h-4" />
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
