"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Table, TableHeader, TableBody, TableRow, TableCell, TableHead } from "@/components/ui/table";
import { formatRelativeTime } from "@/lib/utils";
import { reportsApi } from "@/lib/api";
import { FileText, Search, Download, AlertTriangle, RefreshCw } from "lucide-react";

const formatLabels: Record<string, string> = {
  pdf: "PDF",
  html: "HTML",
  json: "JSON",
};

export default function ReportsPage() {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [pageSize] = useState(20);

  const { data, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: ["reports", { page, pageSize }],
    queryFn: () => reportsApi.list({ page, page_size: pageSize }),
  });

  const reports = data?.items || [];
  const totalReports = data?.total || 0;

  const filteredReports = search
    ? reports.filter(
        (r) =>
          r.title.toLowerCase().includes(search.toLowerCase()) ||
          r.case_id.toLowerCase().includes(search.toLowerCase())
      )
    : reports;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">Reports & Dossiers</h1>
          <p className="text-slate-600 dark:text-slate-400 text-sm">Generated investigation reports and statutory notices</p>
        </div>
        <Button variant="outline" onClick={() => refetch()} disabled={isFetching} className="rounded-xl border-slate-200 dark:border-slate-800">
          <RefreshCw className={`w-4 h-4 mr-2 ${isFetching ? "animate-spin text-primary" : ""}`} />
          Refresh
        </Button>
      </div>

      <Card className="rounded-2xl border-slate-200 dark:border-slate-800 bg-white dark:bg-[#1E2024] shadow-sm">
        <CardHeader className="pb-3 border-b border-slate-100 dark:border-slate-800">
          <CardTitle className="text-lg font-bold text-slate-900 dark:text-white flex items-center justify-between">
            <span>All Generated Reports ({totalReports})</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 pt-4">
          <div className="relative max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <Input
              placeholder="Search by title or case ID..."
              className="pl-9 rounded-xl border-slate-200 dark:border-slate-800 focus-visible:ring-primary"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          {error && (
            <div className="p-3.5 rounded-xl bg-destructive/10 border border-destructive/20 text-destructive text-sm flex items-center gap-2 font-medium">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              Failed to load reports: {error instanceof Error ? error.message : "Unknown error"}
            </div>
          )}

          {isLoading ? (
            <div className="py-12 text-center text-slate-500 dark:text-slate-400 text-sm font-medium">Loading reports...</div>
          ) : filteredReports.length === 0 ? (
            <div className="py-12 flex flex-col items-center justify-center text-slate-500 dark:text-slate-400">
              <FileText className="w-12 h-12 mb-4 opacity-30 text-primary" />
              <p className="text-base font-bold text-slate-800 dark:text-slate-200">No Reports Found</p>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Generate a report from a case or graph to see it listed here</p>
            </div>
          ) : (
            <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800">
              <Table>
                <TableHeader className="bg-slate-50 dark:bg-slate-900/60">
                  <TableRow className="border-b border-slate-200 dark:border-slate-800">
                    <TableHead className="font-bold text-slate-700 dark:text-slate-300">Title</TableHead>
                    <TableHead className="font-bold text-slate-700 dark:text-slate-300">Case</TableHead>
                    <TableHead className="font-bold text-slate-700 dark:text-slate-300">Format</TableHead>
                    <TableHead className="font-bold text-slate-700 dark:text-slate-300">Generated By</TableHead>
                    <TableHead className="font-bold text-slate-700 dark:text-slate-300">Created</TableHead>
                    <TableHead className="font-bold text-slate-700 dark:text-slate-300 text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredReports.map((r) => (
                    <TableRow key={r.id} className="border-b border-slate-100 dark:border-slate-800/60 hover:bg-slate-50 dark:hover:bg-slate-800/40 transition-colors">
                      <TableCell className="font-medium text-slate-900 dark:text-slate-100">
                        <div className="flex items-center gap-2">
                          {(() => {
                            const nType = (r.findings as Record<string, any> | undefined)?.notice_type || "";
                            if (nType === "section_106_bnss_seizure" || r.title?.includes("Asset Seizure")) {
                              return (
                                <Badge variant="secondary" className="bg-red-500/10 text-red-700 dark:text-red-400 border border-red-200 dark:border-red-800 text-[10px] font-semibold whitespace-nowrap">
                                  🚨 Sec 106 BNSS Seizure
                                </Badge>
                              );
                            }
                            if (nType === "section_106_bnss_debit_lien" || r.title?.includes("Total Debit Lien")) {
                              return (
                                <Badge variant="secondary" className="bg-amber-500/10 text-amber-700 dark:text-amber-400 border border-amber-200 dark:border-amber-800 text-[10px] font-semibold whitespace-nowrap">
                                  🛑 Sec 106(3) Debit Lien
                                </Badge>
                              );
                            }
                            if (nType === "section_94_bnss_targeted_lien" || r.title?.includes("Targeted Debit Lien")) {
                              return (
                                <Badge variant="secondary" className="bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800 text-[10px] font-semibold whitespace-nowrap">
                                  ⚖️ Sec 94 Targeted Lien
                                </Badge>
                              );
                            }
                            if (r.title?.includes("Section 91") || nType === "section_91_crpc") {
                              return (
                                <Badge variant="secondary" className="bg-purple-500/10 text-purple-700 dark:text-purple-300 border border-purple-200 dark:border-purple-800 text-[10px] font-semibold whitespace-nowrap">
                                  Sec 91 CrPC
                                </Badge>
                              );
                            }
                            return null;
                          })()}
                          <span className="truncate max-w-[320px] font-semibold">{r.title}</span>
                        </div>
                      </TableCell>
                      <TableCell className="font-mono text-xs text-slate-600 dark:text-slate-400 font-medium">{r.case_id?.slice(0, 8)}...</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="uppercase text-[11px] font-mono border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300">{formatLabels[r.format] || r.format}</Badge>
                      </TableCell>
                      <TableCell className="text-slate-600 dark:text-slate-400 text-xs font-mono">{r.generated_by?.slice(0, 8)}...</TableCell>
                      <TableCell className="text-slate-600 dark:text-slate-400 text-xs">{formatRelativeTime(r.created_at)}</TableCell>
                      <TableCell className="text-right">
                        <a
                          href={`/api/reports/${r.id}/download`}
                          target="_blank"
                          rel="noopener noreferrer"
                          download
                          title="Download report file"
                          className="inline-flex items-center justify-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-primary hover:bg-primary/90 text-white text-xs font-semibold shadow-sm transition-all"
                        >
                          <Download className="w-3.5 h-3.5" />
                          Download
                        </a>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
